import {
  CalendarDays,
  CalendarHeart,
  FileUser,
  IdCard,
  ScanQrCode,
  Signature,
} from "lucide-react";
import { IMenuItem } from "@/models/InteractionMenu/type";
import GeneralCalendar from "../GeneralCalendar";
import PersonalCalendar from "../PersonalCalendar";
import UserInfo from "../UserInfo";
import VerifyCCCD from "../VerifyCCCD";
import Procedures from "../Procedures";
import AppointmentChecking from "../AppointmentChecking";

export const interactionMenu: Record<string, IMenuItem[]> = {
  guest: [
    {
      id: 1,
      title: "Xác thực thông tin",
      description: "Xác thực thông tin căn cước công dân qua máy đọc",
      icon: IdCard,
      action: "dialog",
      component: VerifyCCCD,
      requiredProps: [],
    },
    {
      id: 2,
      title: "Check-in lịch hẹn",
      description: "Check-in lịch hẹn bạn đã đặt để liên hệ với bên cần hẹn",
      icon: ScanQrCode,
      action: "dialog",
      component: AppointmentChecking,
      requiredProps: [],
    },
    {
      id: 3,
      title: "Thủ tục hành chính",
      description:
        "Thông tin về các thủ tục hành chính cơ bản của Viện Khoa học Kĩ thuật Bưu điện",
      icon: Signature,
      action: "drawer",
      component: Procedures,
      requiredProps: [],
    },
  ],
  student: [
    {
      id: 1,
      title: "Lịch học chung",
      description: "Lịch học chung của tất cả sinh viên",
      icon: CalendarDays,
      action: "sheet",
      component: GeneralCalendar,
      requiredProps: ["currentRole"],
    },
    {
      id: 2,
      title: "Lịch học của tôi",
      description: "Lịch học cá nhân của sinh viên",
      icon: CalendarHeart,
      action: "sheet",
      component: PersonalCalendar,
      requiredProps: ["currentRole", "currentCccd"],
    },
    {
      id: 3,
      title: "Thông tin của tôi",
      description: "Thông tin cá nhân của sinh viên",
      icon: FileUser,
      action: "drawer",
      component: UserInfo,
      requiredProps: ["currentCccd"],
    },
    {
      id: 4,
      title: "Xác thực thông tin",
      description: "Xác thực thông tin căn cước công dân qua máy đọc",
      icon: IdCard,
      action: "dialog",
      component: VerifyCCCD,
      requiredProps: [],
    },
    {
      id: 5,
      title: "Check-in lịch hẹn",
      description: "Check-in lịch hẹn bạn đã đặt để liên hệ với bên cần hẹn",
      icon: ScanQrCode,
      action: "dialog",
      component: AppointmentChecking,
      requiredProps: [],
    },
    {
      id: 6,
      title: "Thủ tục hành chính",
      description:
        "Thông tin về các thủ tục hành chính cơ bản của Viện Khoa học Kĩ thuật Bưu điện",
      icon: Signature,
      action: "drawer",
      component: Procedures,
      requiredProps: [],
    },
  ],
  instructor: [
    {
      id: 1,
      title: "Lịch giảng dạy chung",
      description: "Lịch giảng dạy chung của tất cả giảng viên",
      icon: CalendarDays,
      action: "sheet",
      component: GeneralCalendar,
      requiredProps: ["currentRole"],
    },
    {
      id: 2,
      title: "Lịch giảng dạy của tôi",
      description: "Lịch giảng dạy cá nhân của giảng viên",
      icon: CalendarHeart,
      action: "sheet",
      component: PersonalCalendar,
      requiredProps: ["currentRole", "currentCccd"],
    },
    {
      id: 3,
      title: "Thông tin của tôi",
      description: "Thông tin cá nhân của giảng viên",
      icon: FileUser,
      action: "drawer",
      component: UserInfo,
      requiredProps: ["currentCccd"],
    },
    {
      id: 4,
      title: "Xác thực thông tin",
      description: "Xác thực thông tin căn cước công dân qua máy đọc",
      icon: IdCard,
      action: "dialog",
      component: VerifyCCCD,
      requiredProps: [],
    },
    {
      id: 5,
      title: "Check-in lịch hẹn",
      description: "Check-in lịch hẹn bạn đã đặt để liên hệ với bên cần hẹn",
      icon: ScanQrCode,
      action: "dialog",
      component: AppointmentChecking,
      requiredProps: [],
    },
    {
      id: 6,
      title: "Thủ tục hành chính",
      description:
        "Thông tin về các thủ tục hành chính cơ bản của Viện Khoa học Kĩ thuật Bưu điện",
      icon: Signature,
      action: "drawer",
      component: Procedures,
      requiredProps: [],
    },
  ],
  staff: [
    {
      id: 1,
      title: "Lịch công tác chung",
      description: "Lịch công tác chung của tất cả cán bộ",
      icon: CalendarDays,
      action: "sheet",
      component: GeneralCalendar,
      requiredProps: ["currentRole"],
    },
    {
      id: 2,
      title: "Lịch công tác của tôi",
      description: "Lịch công tác cá nhân của cán bộ",
      icon: CalendarHeart,
      action: "sheet",
      component: PersonalCalendar,
      requiredProps: ["currentRole", "currentCccd"],
    },
    {
      id: 3,
      title: "Thông tin của tôi",
      description: "Thông tin cá nhân của cán bộ",
      icon: FileUser,
      action: "drawer",
      component: UserInfo,
      requiredProps: ["currentCccd"],
    },
    {
      id: 4,
      title: "Xác thực thông tin",
      description: "Xác thực thông tin căn cước công dân qua máy đọc",
      icon: IdCard,
      action: "dialog",
      component: VerifyCCCD,
      requiredProps: [],
    },
    {
      id: 5,
      title: "Check-in lịch hẹn",
      description: "Check-in lịch hẹn bạn đã đặt để liên hệ với bên cần hẹn",
      icon: ScanQrCode,
      action: "dialog",
      component: AppointmentChecking,
      requiredProps: [],
    },
    {
      id: 6,
      title: "Thủ tục hành chính",
      description:
        "Thông tin về các thủ tục hành chính cơ bản của Viện Khoa học Kĩ thuật Bưu điện",
      icon: Signature,
      action: "drawer",
      component: Procedures,
      requiredProps: [],
    },
  ],
};
