export const departmentList = [
  {
    id: 1,
    code: "BLĐ",
    name: "Ban lãnh đạo",
    description: "",
    headOfDepartment: "Ngô Quốc Dũng",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Ngô Quốc Dũng",
        position: "Phó viện trưởng",
        email: "nqd@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Trần Thiện Chính",
        position: "Phó viện trưởng",
        email: "ttc@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
  {
    id: 2,
    code: "PTH",
    name: "Phòng Tổng hợp",
    description: "",
    headOfDepartment: "Vũ Thị Lan Hương",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Vũ Thị Lan Hương",
        position: "Trưởng phòng",
        email: "vtlh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Đinh Thị Oanh",
        position: "Nhân viên",
        email: "dta@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 3,
        name: "Lương Hồng Minh",
        position: "Nhân viên",
        email: "lhm@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 4,
        name: "Trần Thị Minh Thìn",
        position: "Nhân viên",
        email: "ttmt@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 5,
        name: "Đặng Thị Tố Uyên",
        position: "Nhân viên",
        email: "dtty@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
  {
    id: 3,
    code: "PKHCNVKHKD",
    name: "Phòng Khoa học công nghệ và kế hoạch kinh doanh",
    description: "",
    headOfDepartment: "Vũ Hồng Sơn",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Vũ Hồng Sơn",
        position: "Trưởng phòng",
        email: "vhs@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Nguyễn Thị Phương Nam",
        position: "Nhân viên",
        email: "ntpn@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 3,
        name: "Trần Hoàng Diệu",
        position: "Nhân viên",
        email: "thd@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 4,
        name: "Đỗ Thị Nhàn",
        position: "Nhân viên",
        email: "dtn@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
  {
    id: 4,
    code: "PTVTK",
    name: "Phòng Tư vấn thiết kế",
    description: "",
    headOfDepartment: "Thái Minh Quân",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Thái Minh Quân",
        position: "Phó trưởng phòng",
        email: "tmq@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Trần Trung Phong",
        position: "Nhân viên",
        email: "ttp@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 3,
        name: "Ngô Thị Mỹ Hà",
        position: "Nhân viên",
        email: "ntmh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
  {
    id: 5,
    code: "PĐLKĐVTCCL",
    name: "Phòng Đo lường kiểm định và tiêu chuẩn chất lượng",
    description: "",
    headOfDepartment: "Đào Đức Dương",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Đào Đức Dương",
        position: "Phó trưởng phòng",
        email: "ddd@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Trịnh Bảo Khánh",
        position: "Nhân viên",
        email: "tbk@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
  {
    id: 6,
    code: "PUDVCGCN",
    name: "Phòng Ứng dụng và chuyển giao công nghệ",
    description: "",
    headOfDepartment: "Nguyễn Việt Dũng",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Nguyễn Việt Dũng",
        position: "Phó trưởng phòng",
        email: "nvd@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Đỗ Diệu Hương",
        position: "Nhân viên",
        email: "ddh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 3,
        name: "Trần Quốc Hưng",
        position: "Nhân viên",
        email: "tqh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 4,
        name: "Đỗ Hương Hà",
        position: "Nhân viên",
        email: "dhh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 5,
        name: "Đào Thu Hiền",
        position: "Nhân viên",
        email: "dth@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
  {
    id: 7,
    code: "PNCPTCNS",
    name: "Phòng Nghiên cứu phát triển công nghệ số",
    description: "",
    headOfDepartment: "Đặng Anh Tuấn",
    workingDays: [2, 7],
    workingHours: [8, 17.3],
    staffs: [
      {
        id: 1,
        name: "Đặng Anh Tuấn",
        position: "Phó trưởng phòng",
        email: "dat@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 2,
        name: "Phan Lý Huỳnh",
        position: "Nhân viên",
        email: "plh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 3,
        name: "Trần Quang Đại",
        position: "Nhân viên",
        email: "tqd@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 4,
        name: "Nguyễn Việt Dũng",
        position: "Nhân viên",
        email: "nvd@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 5,
        name: "Vũ Văn Thương",
        position: "Nhân viên",
        email: "vvt@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      {
        id: 6,
        name: "Phạm Đình Chung",
        position: "Phó trưởng phòng",
        email: "pdc@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
    ],
  },
];
